name: Terraform oidc Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write   # Required for requesting OIDC JWT token
  contents: read    # Required to checkout the repo

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::866771492404:role/YOUR_ACTUAL_IAM_ROLE_NAME  # Ensure this matches your AWS Role Name
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
