name: AWS OIDC Authentication

on:
  push:
    branches:
      - main # Triggers the workflow on pushes to the main branch

# These permissions are required to interact with GitHub's OIDC Token endpoint
permissions:
  id-token: write # Required to request the OIDC JWT token
  contents: read  # Required to checkout the repository code

jobs:
  aws-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::814203451643:role/oidc-role
          aws-region: us-east-1 # Update this to your target AWS region
          
      - name: Verify AWS Connection
        run: |
          # This command verifies that the role was successfully assumed
          aws sts get-caller-identity
